//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Campaign.CouponServices.Session {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebserviceException", Namespace="urn:api.broadmail.de/soap11/Session")]
    [System.SerializableAttribute()]
    internal partial class WebserviceException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private object causeField;
        
        private string messageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal object cause {
            get {
                return this.causeField;
            }
            set {
                if ((object.ReferenceEquals(this.causeField, value) != true)) {
                    this.causeField = value;
                    this.RaisePropertyChanged("cause");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        internal string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:api.broadmail.de/soap11/Session", ConfigurationName="Session.SessionWebservice")]
    internal interface SessionWebservice {
        
        // CODEGEN: Generating message contract since element name in0 from namespace urn:api.broadmail.de/soap11/Session is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Campaign.CouponServices.Session.WebserviceException), Action="", Name="fault")]
        Campaign.CouponServices.Session.setMediaTypeResponse setMediaType(Campaign.CouponServices.Session.setMediaTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Campaign.CouponServices.Session.setMediaTypeResponse> setMediaTypeAsync(Campaign.CouponServices.Session.setMediaTypeRequest request);
        
        // CODEGEN: Generating message contract since element name in0 from namespace urn:api.broadmail.de/soap11/Session is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Campaign.CouponServices.Session.WebserviceException), Action="", Name="fault")]
        Campaign.CouponServices.Session.getMediaTypeResponse getMediaType(Campaign.CouponServices.Session.getMediaTypeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Campaign.CouponServices.Session.getMediaTypeResponse> getMediaTypeAsync(Campaign.CouponServices.Session.getMediaTypeRequest request);
        
        // CODEGEN: Generating message contract since element name in0 from namespace urn:api.broadmail.de/soap11/Session is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Campaign.CouponServices.Session.WebserviceException), Action="", Name="fault")]
        Campaign.CouponServices.Session.logoutResponse logout(Campaign.CouponServices.Session.logoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Campaign.CouponServices.Session.logoutResponse> logoutAsync(Campaign.CouponServices.Session.logoutRequest request);
        
        // CODEGEN: Generating message contract since element name in1 from namespace urn:api.broadmail.de/soap11/Session is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Campaign.CouponServices.Session.WebserviceException), Action="", Name="fault")]
        Campaign.CouponServices.Session.loginResponse login(Campaign.CouponServices.Session.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Campaign.CouponServices.Session.loginResponse> loginAsync(Campaign.CouponServices.Session.loginRequest request);
        
        // CODEGEN: Generating message contract since element name in0 from namespace urn:api.broadmail.de/soap11/Session is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Campaign.CouponServices.Session.WebserviceException), Action="", Name="fault")]
        Campaign.CouponServices.Session.setLocaleResponse setLocale(Campaign.CouponServices.Session.setLocaleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Campaign.CouponServices.Session.setLocaleResponse> setLocaleAsync(Campaign.CouponServices.Session.setLocaleRequest request);
        
        // CODEGEN: Generating message contract since element name in0 from namespace urn:api.broadmail.de/soap11/Session is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Campaign.CouponServices.Session.WebserviceException), Action="", Name="fault")]
        Campaign.CouponServices.Session.getLocaleResponse getLocale(Campaign.CouponServices.Session.getLocaleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Campaign.CouponServices.Session.getLocaleResponse> getLocaleAsync(Campaign.CouponServices.Session.getLocaleRequest request);
        
        // CODEGEN: Generating message contract since element name getVersionReturn from namespace urn:api.broadmail.de/soap11/Session is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Campaign.CouponServices.Session.WebserviceException), Action="", Name="fault")]
        Campaign.CouponServices.Session.getVersionResponse getVersion(Campaign.CouponServices.Session.getVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<Campaign.CouponServices.Session.getVersionResponse> getVersionAsync(Campaign.CouponServices.Session.getVersionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class setMediaTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setMediaType", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public Campaign.CouponServices.Session.setMediaTypeRequestBody Body;
        
        public setMediaTypeRequest() {
        }
        
        public setMediaTypeRequest(Campaign.CouponServices.Session.setMediaTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/Session")]
    internal partial class setMediaTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string in1;
        
        public setMediaTypeRequestBody() {
        }
        
        public setMediaTypeRequestBody(string in0, string in1) {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class setMediaTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setMediaTypeResponse", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public Campaign.CouponServices.Session.setMediaTypeResponseBody Body;
        
        public setMediaTypeResponse() {
        }
        
        public setMediaTypeResponse(Campaign.CouponServices.Session.setMediaTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class setMediaTypeResponseBody {
        
        public setMediaTypeResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getMediaTypeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMediaType", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public Campaign.CouponServices.Session.getMediaTypeRequestBody Body;
        
        public getMediaTypeRequest() {
        }
        
        public getMediaTypeRequest(Campaign.CouponServices.Session.getMediaTypeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/Session")]
    internal partial class getMediaTypeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        public getMediaTypeRequestBody() {
        }
        
        public getMediaTypeRequestBody(string in0) {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getMediaTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMediaTypeResponse", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public Campaign.CouponServices.Session.getMediaTypeResponseBody Body;
        
        public getMediaTypeResponse() {
        }
        
        public getMediaTypeResponse(Campaign.CouponServices.Session.getMediaTypeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/Session")]
    internal partial class getMediaTypeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getMediaTypeReturn;
        
        public getMediaTypeResponseBody() {
        }
        
        public getMediaTypeResponseBody(string getMediaTypeReturn) {
            this.getMediaTypeReturn = getMediaTypeReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class logoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logout", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public Campaign.CouponServices.Session.logoutRequestBody Body;
        
        public logoutRequest() {
        }
        
        public logoutRequest(Campaign.CouponServices.Session.logoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/Session")]
    internal partial class logoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        public logoutRequestBody() {
        }
        
        public logoutRequestBody(string in0) {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class logoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logoutResponse", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public Campaign.CouponServices.Session.logoutResponseBody Body;
        
        public logoutResponse() {
        }
        
        public logoutResponse(Campaign.CouponServices.Session.logoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class logoutResponseBody {
        
        public logoutResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public Campaign.CouponServices.Session.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(Campaign.CouponServices.Session.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/Session")]
    internal partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long in0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string in1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string in2;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(long in0, string in1, string in2) {
            this.in0 = in0;
            this.in1 = in1;
            this.in2 = in2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public Campaign.CouponServices.Session.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(Campaign.CouponServices.Session.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/Session")]
    internal partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginReturn;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(string loginReturn) {
            this.loginReturn = loginReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class setLocaleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setLocale", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public Campaign.CouponServices.Session.setLocaleRequestBody Body;
        
        public setLocaleRequest() {
        }
        
        public setLocaleRequest(Campaign.CouponServices.Session.setLocaleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/Session")]
    internal partial class setLocaleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string in1;
        
        public setLocaleRequestBody() {
        }
        
        public setLocaleRequestBody(string in0, string in1) {
            this.in0 = in0;
            this.in1 = in1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class setLocaleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setLocaleResponse", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public Campaign.CouponServices.Session.setLocaleResponseBody Body;
        
        public setLocaleResponse() {
        }
        
        public setLocaleResponse(Campaign.CouponServices.Session.setLocaleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class setLocaleResponseBody {
        
        public setLocaleResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getLocaleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLocale", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public Campaign.CouponServices.Session.getLocaleRequestBody Body;
        
        public getLocaleRequest() {
        }
        
        public getLocaleRequest(Campaign.CouponServices.Session.getLocaleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/Session")]
    internal partial class getLocaleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string in0;
        
        public getLocaleRequestBody() {
        }
        
        public getLocaleRequestBody(string in0) {
            this.in0 = in0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getLocaleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLocaleResponse", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public Campaign.CouponServices.Session.getLocaleResponseBody Body;
        
        public getLocaleResponse() {
        }
        
        public getLocaleResponse(Campaign.CouponServices.Session.getLocaleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/Session")]
    internal partial class getLocaleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getLocaleReturn;
        
        public getLocaleResponseBody() {
        }
        
        public getLocaleResponseBody(string getLocaleReturn) {
            this.getLocaleReturn = getLocaleReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getVersionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVersion", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public Campaign.CouponServices.Session.getVersionRequestBody Body;
        
        public getVersionRequest() {
        }
        
        public getVersionRequest(Campaign.CouponServices.Session.getVersionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    internal partial class getVersionRequestBody {
        
        public getVersionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class getVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVersionResponse", Namespace="urn:api.broadmail.de/soap11/Session", Order=0)]
        public Campaign.CouponServices.Session.getVersionResponseBody Body;
        
        public getVersionResponse() {
        }
        
        public getVersionResponse(Campaign.CouponServices.Session.getVersionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="urn:api.broadmail.de/soap11/Session")]
    internal partial class getVersionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getVersionReturn;
        
        public getVersionResponseBody() {
        }
        
        public getVersionResponseBody(string getVersionReturn) {
            this.getVersionReturn = getVersionReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface SessionWebserviceChannel : Campaign.CouponServices.Session.SessionWebservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class SessionWebserviceClient : System.ServiceModel.ClientBase<Campaign.CouponServices.Session.SessionWebservice>, Campaign.CouponServices.Session.SessionWebservice {
        
        public SessionWebserviceClient() {
        }
        
        public SessionWebserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SessionWebserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionWebserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SessionWebserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Campaign.CouponServices.Session.setMediaTypeResponse Campaign.CouponServices.Session.SessionWebservice.setMediaType(Campaign.CouponServices.Session.setMediaTypeRequest request) {
            return base.Channel.setMediaType(request);
        }
        
        public void setMediaType(string in0, string in1) {
            Campaign.CouponServices.Session.setMediaTypeRequest inValue = new Campaign.CouponServices.Session.setMediaTypeRequest();
            inValue.Body = new Campaign.CouponServices.Session.setMediaTypeRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            Campaign.CouponServices.Session.setMediaTypeResponse retVal = ((Campaign.CouponServices.Session.SessionWebservice)(this)).setMediaType(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Campaign.CouponServices.Session.setMediaTypeResponse> Campaign.CouponServices.Session.SessionWebservice.setMediaTypeAsync(Campaign.CouponServices.Session.setMediaTypeRequest request) {
            return base.Channel.setMediaTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Campaign.CouponServices.Session.setMediaTypeResponse> setMediaTypeAsync(string in0, string in1) {
            Campaign.CouponServices.Session.setMediaTypeRequest inValue = new Campaign.CouponServices.Session.setMediaTypeRequest();
            inValue.Body = new Campaign.CouponServices.Session.setMediaTypeRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            return ((Campaign.CouponServices.Session.SessionWebservice)(this)).setMediaTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Campaign.CouponServices.Session.getMediaTypeResponse Campaign.CouponServices.Session.SessionWebservice.getMediaType(Campaign.CouponServices.Session.getMediaTypeRequest request) {
            return base.Channel.getMediaType(request);
        }
        
        public string getMediaType(string in0) {
            Campaign.CouponServices.Session.getMediaTypeRequest inValue = new Campaign.CouponServices.Session.getMediaTypeRequest();
            inValue.Body = new Campaign.CouponServices.Session.getMediaTypeRequestBody();
            inValue.Body.in0 = in0;
            Campaign.CouponServices.Session.getMediaTypeResponse retVal = ((Campaign.CouponServices.Session.SessionWebservice)(this)).getMediaType(inValue);
            return retVal.Body.getMediaTypeReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Campaign.CouponServices.Session.getMediaTypeResponse> Campaign.CouponServices.Session.SessionWebservice.getMediaTypeAsync(Campaign.CouponServices.Session.getMediaTypeRequest request) {
            return base.Channel.getMediaTypeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Campaign.CouponServices.Session.getMediaTypeResponse> getMediaTypeAsync(string in0) {
            Campaign.CouponServices.Session.getMediaTypeRequest inValue = new Campaign.CouponServices.Session.getMediaTypeRequest();
            inValue.Body = new Campaign.CouponServices.Session.getMediaTypeRequestBody();
            inValue.Body.in0 = in0;
            return ((Campaign.CouponServices.Session.SessionWebservice)(this)).getMediaTypeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Campaign.CouponServices.Session.logoutResponse Campaign.CouponServices.Session.SessionWebservice.logout(Campaign.CouponServices.Session.logoutRequest request) {
            return base.Channel.logout(request);
        }
        
        public void logout(string in0) {
            Campaign.CouponServices.Session.logoutRequest inValue = new Campaign.CouponServices.Session.logoutRequest();
            inValue.Body = new Campaign.CouponServices.Session.logoutRequestBody();
            inValue.Body.in0 = in0;
            Campaign.CouponServices.Session.logoutResponse retVal = ((Campaign.CouponServices.Session.SessionWebservice)(this)).logout(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Campaign.CouponServices.Session.logoutResponse> Campaign.CouponServices.Session.SessionWebservice.logoutAsync(Campaign.CouponServices.Session.logoutRequest request) {
            return base.Channel.logoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Campaign.CouponServices.Session.logoutResponse> logoutAsync(string in0) {
            Campaign.CouponServices.Session.logoutRequest inValue = new Campaign.CouponServices.Session.logoutRequest();
            inValue.Body = new Campaign.CouponServices.Session.logoutRequestBody();
            inValue.Body.in0 = in0;
            return ((Campaign.CouponServices.Session.SessionWebservice)(this)).logoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Campaign.CouponServices.Session.loginResponse Campaign.CouponServices.Session.SessionWebservice.login(Campaign.CouponServices.Session.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public string login(long in0, string in1, string in2) {
            Campaign.CouponServices.Session.loginRequest inValue = new Campaign.CouponServices.Session.loginRequest();
            inValue.Body = new Campaign.CouponServices.Session.loginRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            inValue.Body.in2 = in2;
            Campaign.CouponServices.Session.loginResponse retVal = ((Campaign.CouponServices.Session.SessionWebservice)(this)).login(inValue);
            return retVal.Body.loginReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Campaign.CouponServices.Session.loginResponse> Campaign.CouponServices.Session.SessionWebservice.loginAsync(Campaign.CouponServices.Session.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Campaign.CouponServices.Session.loginResponse> loginAsync(long in0, string in1, string in2) {
            Campaign.CouponServices.Session.loginRequest inValue = new Campaign.CouponServices.Session.loginRequest();
            inValue.Body = new Campaign.CouponServices.Session.loginRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            inValue.Body.in2 = in2;
            return ((Campaign.CouponServices.Session.SessionWebservice)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Campaign.CouponServices.Session.setLocaleResponse Campaign.CouponServices.Session.SessionWebservice.setLocale(Campaign.CouponServices.Session.setLocaleRequest request) {
            return base.Channel.setLocale(request);
        }
        
        public void setLocale(string in0, string in1) {
            Campaign.CouponServices.Session.setLocaleRequest inValue = new Campaign.CouponServices.Session.setLocaleRequest();
            inValue.Body = new Campaign.CouponServices.Session.setLocaleRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            Campaign.CouponServices.Session.setLocaleResponse retVal = ((Campaign.CouponServices.Session.SessionWebservice)(this)).setLocale(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Campaign.CouponServices.Session.setLocaleResponse> Campaign.CouponServices.Session.SessionWebservice.setLocaleAsync(Campaign.CouponServices.Session.setLocaleRequest request) {
            return base.Channel.setLocaleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Campaign.CouponServices.Session.setLocaleResponse> setLocaleAsync(string in0, string in1) {
            Campaign.CouponServices.Session.setLocaleRequest inValue = new Campaign.CouponServices.Session.setLocaleRequest();
            inValue.Body = new Campaign.CouponServices.Session.setLocaleRequestBody();
            inValue.Body.in0 = in0;
            inValue.Body.in1 = in1;
            return ((Campaign.CouponServices.Session.SessionWebservice)(this)).setLocaleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Campaign.CouponServices.Session.getLocaleResponse Campaign.CouponServices.Session.SessionWebservice.getLocale(Campaign.CouponServices.Session.getLocaleRequest request) {
            return base.Channel.getLocale(request);
        }
        
        public string getLocale(string in0) {
            Campaign.CouponServices.Session.getLocaleRequest inValue = new Campaign.CouponServices.Session.getLocaleRequest();
            inValue.Body = new Campaign.CouponServices.Session.getLocaleRequestBody();
            inValue.Body.in0 = in0;
            Campaign.CouponServices.Session.getLocaleResponse retVal = ((Campaign.CouponServices.Session.SessionWebservice)(this)).getLocale(inValue);
            return retVal.Body.getLocaleReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Campaign.CouponServices.Session.getLocaleResponse> Campaign.CouponServices.Session.SessionWebservice.getLocaleAsync(Campaign.CouponServices.Session.getLocaleRequest request) {
            return base.Channel.getLocaleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Campaign.CouponServices.Session.getLocaleResponse> getLocaleAsync(string in0) {
            Campaign.CouponServices.Session.getLocaleRequest inValue = new Campaign.CouponServices.Session.getLocaleRequest();
            inValue.Body = new Campaign.CouponServices.Session.getLocaleRequestBody();
            inValue.Body.in0 = in0;
            return ((Campaign.CouponServices.Session.SessionWebservice)(this)).getLocaleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Campaign.CouponServices.Session.getVersionResponse Campaign.CouponServices.Session.SessionWebservice.getVersion(Campaign.CouponServices.Session.getVersionRequest request) {
            return base.Channel.getVersion(request);
        }
        
        public string getVersion() {
            Campaign.CouponServices.Session.getVersionRequest inValue = new Campaign.CouponServices.Session.getVersionRequest();
            inValue.Body = new Campaign.CouponServices.Session.getVersionRequestBody();
            Campaign.CouponServices.Session.getVersionResponse retVal = ((Campaign.CouponServices.Session.SessionWebservice)(this)).getVersion(inValue);
            return retVal.Body.getVersionReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Campaign.CouponServices.Session.getVersionResponse> Campaign.CouponServices.Session.SessionWebservice.getVersionAsync(Campaign.CouponServices.Session.getVersionRequest request) {
            return base.Channel.getVersionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Campaign.CouponServices.Session.getVersionResponse> getVersionAsync() {
            Campaign.CouponServices.Session.getVersionRequest inValue = new Campaign.CouponServices.Session.getVersionRequest();
            inValue.Body = new Campaign.CouponServices.Session.getVersionRequestBody();
            return ((Campaign.CouponServices.Session.SessionWebservice)(this)).getVersionAsync(inValue);
        }
    }
}
